version: '3.7'

services:
  web:
    build:
      context: ./../..
      dockerfile: ./composer/web/Dockerfile

    command: uvicorn dev_main:app --host 0.0.0.0 --reload --reload
#    command: uvicorn test_apps:app --host 0.0.0.0 --reload
#    command: ls /app
#    command: python3 /app/dev_run.py
#    volumes:
#      - .:/app
    ports:
      - 8008:8000
