db:
  host: 192.168.18.36
  port: 27018
  username: 'admin-doc'
  password: '123456'
  authSource: 'lv-docs'
#  replicaSet: ''
  authMechanism: SCRAM-SHA-1
front-end:
  static: C:/projects/python/fasty-web-file/app_front_end/static
  server-templates: C:/projects/python/fasty-web-file/webapp/templates
  api-url: 'http://172.16.7.25:8012/api'
single-page-application:
  main-page: index.html
jwt:
  SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
  ALGORITHM: HS256
  ACCESS_TOKEN_EXPIRE_MINUTES: 480
core:

  logging:
    version: 1
    formatters:
      formatter:
        format: "[%(asctime)s] [%(levelname)s] [%(name)s]: %(message)s"
    handlers:
      console:
        class: "logging.StreamHandler"
        level: "DEBUG"
        formatter: "formatter"
        stream: "ext://sys.stderr"
    root:
      level: "DEBUG"
      handlers: ["console"]
host:
  bind: 172.16.7.25
  port: 8012