db:
  host: 172.16.13.72
  port: 27017
  username: 'root'
  password: '123456'
  authSource: 'admin'
  #  replicaSet: ''
  authMechanism: SCRAM-SHA-1
front-end:
  static: ./resource/static
  server-templates: ./resource/server/templates
  api-url: http://172.16.13.72:8008/api

single-page-application:
  main-page: index.html
jwt:
  SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
  ALGORITHM: HS256
  ACCESS_TOKEN_EXPIRE_MINUTES: 480
core:

  logging:
    version: 1
    formatters:
      formatter:
        format: "[%(asctime)s] [%(levelname)s] [%(name)s]: %(message)s"
    handlers:
      console:
        class: "logging.StreamHandler"
        level: "DEBUG"
        formatter: "formatter"
        stream: "ext://sys.stderr"
    root:
      level: "DEBUG"
      handlers: ["console"]
host:
  bind:  0.0.0.0.0
  port: 8000
  schema: http
  domain:  0.0.0.0.0


storage:
  type: mongodb
  s3:
    access-key-id: AKIAS7SHGPQS4TK52EG7
    secret-access-key: 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
    tmp-directory: //192.168.18.36/Share/s3-tmp
  file:
    location: //192.168.18.36/Share/s3-tmp

  mongodb:
    host: 172.16.13.72
    port: 27017
    username: 'root'
    password: '123456'
    authSource: 'admin'
    #  replicaSet: ''
    authMechanism: SCRAM-SHA-1

message:
  type: kafka
  temp-dir: /app/tmp
  kafka:
    brokers:
      - 172.16.13.72:9092
content-processing:
  temp-dir: /app/content-processing