version: '3.4'

services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'EST5EDT'
    networks:
      - default
    ports:
      - "147:137/udp"
      - "148:138/udp"
      - "149:139/tcp"
      - "455:445/tcp"
#    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /file-service-share-tmp:/file-service-share-tmp-inside-container:z
    command: '-s "Mount;/file-service-share-tmp-inside-container" -s "file service Volume;/file-service-share-tmp-inside-container;no;no;no;bob" -p'

networks:
  default: