version: '3.7'
services:
  consumer-file-video-thumb:
    build:
      context: ./..
      dockerfile: ./composer/consumer-files-video-create-thumb-dockerfile
    volumes:
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-file-upload/:/app/tmp
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-processing-file/:/app/content-processing
      - ${PATH_LOCAL_DIR_IN_HOST}/consumer/logs/:/app/logs
    command: >
      sh -c "
        python3  /app/broker_consumer_when_file_create_thumb_video.py
        "

#    command: python3  /app/broker_consumer_when_file_uploaded.py


