version: "2.1"
services:
  libreoffice:
    image: lscr.io/linuxserver/libreoffice:latest
    container_name: libreoffice
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${PATH_TO_LIBRE_OFFICE_CONFIG}:/config
    ports:
      - 3000:3000
    restart: unless-stopped