version: '3.7'

services:
  web:
    build:
      context: ./..
      dockerfile: ./composer/web-dockerfile
    volumes:
      - ${WEB_TMP_FILE_UPLOAD}/:/app/tmp
      - ${PROCESS_CONTENT}/:/app/content-processing

    command: uvicorn application:app --host 0.0.0.0 --reload --reload
#    command: uvicorn test_apps:app --host 0.0.0.0 --reload
#    command: ls /app
#    command: python3 /app/dev_run.py
#    volumes:
#      - .:/app
    ports:
      - 8008:8000

#    command: ls ./.. # list all root folders
#    command: mkdir /app/tmp/yes_ok #check can docker access to tmp